apiVersion: v1
kind: Service
metadata:
  name: blockinfrastructure
  namespace: blockinfrastructure
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: blockinfrastructure
  type: ClusterIP