name: Run Test, Deploy Block Infrastructure Core API to Kubernetes Cluster

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_application:
    name: 'Test Application'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: 'Test Application'
        run: 'dotnet test'

  deploy_registry:
    concurrency:
      group: deploy_registry
      cancel-in-progress: true
    name: Build and deploy docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to test-server
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Initialize Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build, Push to Registry
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./src
          file: ./src/BlockInfrastructure-Core/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: kangdroid/blockinfrastructure-core:${{ github.sha }},kangdroid/blockinfrastructure-core:main
          cache-from: type=gha
          cache-to: type=gha,mode=max

  change_infrastructure_code:
    concurrency:
      group: deploy_kubernetes
      cancel-in-progress: true
    name: Deploy to Kubernetes Cluster
    needs: [ deploy_registry, test_application ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          repository: KangDroid/personal-infrastructure
          path: personal-infrastructure
          token: ${{ secrets.GH_TK }}
      - name: Edit Deployment Configuration using yq
        env:
          IMAGE_WITH_TAG: kangdroid/blockinfrastructure-core:${{ github.sha }}
          DEPLOYMENT_FILE_PATH: "argocd/deployment/backend-applications/blockinfrastructure/deployment.yaml"
          CONTAINER_NAME: "wein-konkuk"
        run: |
          yq e "(.spec.template.spec.containers[] | select(.name == strenv(CONTAINER_NAME)).image) = strenv(IMAGE_WITH_TAG)" -i personal-infrastructure/${DEPLOYMENT_FILE_PATH}
      - name: Push to GitHub
        env:
          GH_TOKEN: ${{ secrets.GH_TK }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd personal-infrastructure
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'

          git add -A
          git commit -am "[Feature] Automated: Update Block Infrastructure Image to $IMAGE_TAG";
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          git push --prune https://actions:$GH_TOKEN@github.com/KangDroid/personal-infrastructure