name: Run Test, Deploy to Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_application:
    if: github.event_name == 'pull_request'
    name: 'Test Education Platform Spring App'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2.1
      - name: 'Test Application'
        run: 'gradle clean test'

  deploy_registry:
    name: Build and deploy docker images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout to test-server
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2.1

      - name: 'Build Application BootJar'
        run: 'gradle bootJar'

      - name: Set Image Tag to Environment Variables
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Initialize Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build, Push to Registry
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: kangdroid/education-platform-core:${{ env.IMAGE_TAG }},kangdroid/education-platform-core:main
          cache-from: type=gha
          cache-to: type=gha,mode=max