name: Run Test, Deploy to Docker Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_application:
    name: 'Test Spring App'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2.1
      - name: 'Test Application'
        run: 'gradle clean test'

  deploy_registry:
    name: Build and deploy docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to test-server
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Initialize Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build, Push to Registry
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./BlockInfrastructure-Core/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: kangdroid/blockinfrastructure-core:${{ github.sha }},kangdroid/blockinfrastructure-core:main
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_kubernetes:
    name: Deploy to Kubernetes Cluster
    needs: [ deploy_registry, test_application ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_CLUSTER_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: wein-konkuk
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml
          images: |
            kangdroid/wein-ku:${{ github.sha }}